
// This file has been generated by the GUI designer. Do not modify.
namespace EliteBinds
{
	public partial class InputWidget
	{
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.Label FieldName;
		
		private global::Gtk.Label FieldValue;
		
		private global::Gtk.Button EditButton;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget EliteBinds.InputWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "EliteBinds.InputWidget";
			// Container child EliteBinds.InputWidget.Gtk.Container+ContainerChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.HeightRequest = 20;
			this.hbox1.Name = "hbox1";
			this.hbox1.Homogeneous = true;
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.FieldName = new global::Gtk.Label ();
			this.FieldName.Name = "FieldName";
			this.FieldName.LabelProp = global::Mono.Unix.Catalog.GetString ("label2");
			this.hbox1.Add (this.FieldName);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.FieldName]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.FieldValue = new global::Gtk.Label ();
			this.FieldValue.Name = "FieldValue";
			this.FieldValue.LabelProp = global::Mono.Unix.Catalog.GetString ("label3");
			this.hbox1.Add (this.FieldValue);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.FieldValue]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.EditButton = new global::Gtk.Button ();
			this.EditButton.CanFocus = true;
			this.EditButton.Name = "EditButton";
			this.EditButton.UseUnderline = true;
			this.EditButton.Label = global::Mono.Unix.Catalog.GetString ("Edit");
			this.hbox1.Add (this.EditButton);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.EditButton]));
			w3.PackType = ((global::Gtk.PackType)(1));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			this.Add (this.hbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
