
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	
	private global::Gtk.Action FileAction;
	
	private global::Gtk.Action openAction;
	
	private global::Gtk.Action saveAction;
	
	private global::Gtk.Action ApplyAction;
	
	private global::Gtk.VBox vbox1;
	
	private global::Gtk.Toolbar toolbar1;
	
	private global::Gtk.Notebook notebook4;
	
	private global::Gtk.Label FlightTab;
	
	private global::Gtk.Label SRVTab;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.FileAction = new global::Gtk.Action ("FileAction", global::Mono.Unix.Catalog.GetString ("File"), null, null);
		this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("File");
		w1.Add (this.FileAction, null);
		this.openAction = new global::Gtk.Action ("openAction", null, null, "gtk-open");
		w1.Add (this.openAction, null);
		this.saveAction = new global::Gtk.Action ("saveAction", null, null, "gtk-save");
		w1.Add (this.saveAction, null);
		this.ApplyAction = new global::Gtk.Action ("ApplyAction", global::Mono.Unix.Catalog.GetString ("Apply"), null, "gtk-ok");
		this.ApplyAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Apply");
		w1.Add (this.ApplyAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><toolbar name=\'toolbar1\'><toolitem name=\'openAction\' action=\'openAction\'/><to" +
		"olitem name=\'saveAction\' action=\'saveAction\'/><toolitem name=\'ApplyAction\' actio" +
		"n=\'ApplyAction\'/></toolbar></ui>");
		this.toolbar1 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget ("/toolbar1")));
		this.toolbar1.HeightRequest = 30;
		this.toolbar1.Events = ((global::Gdk.EventMask)(512));
		this.toolbar1.Name = "toolbar1";
		this.toolbar1.ShowArrow = false;
		this.toolbar1.ToolbarStyle = ((global::Gtk.ToolbarStyle)(1));
		this.toolbar1.IconSize = ((global::Gtk.IconSize)(1));
		this.vbox1.Add (this.toolbar1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.toolbar1]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.notebook4 = new global::Gtk.Notebook ();
		this.notebook4.CanFocus = true;
		this.notebook4.Name = "notebook4";
		this.notebook4.CurrentPage = 0;
		// Notebook tab
		global::Gtk.Label w3 = new global::Gtk.Label ();
		w3.Visible = true;
		this.notebook4.Add (w3);
		this.FlightTab = new global::Gtk.Label ();
		this.FlightTab.Name = "FlightTab";
		this.FlightTab.LabelProp = global::Mono.Unix.Catalog.GetString ("Flight Controls");
		this.notebook4.SetTabLabel (w3, this.FlightTab);
		this.FlightTab.ShowAll ();
		// Notebook tab
		global::Gtk.Label w4 = new global::Gtk.Label ();
		w4.Visible = true;
		this.notebook4.Add (w4);
		this.SRVTab = new global::Gtk.Label ();
		this.SRVTab.Name = "SRVTab";
		this.SRVTab.LabelProp = global::Mono.Unix.Catalog.GetString ("SRV Controls");
		this.notebook4.SetTabLabel (w4, this.SRVTab);
		this.SRVTab.ShowAll ();
		this.vbox1.Add (this.notebook4);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.notebook4]));
		w5.Position = 1;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 611;
		this.DefaultHeight = 589;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.openAction.Activated += new global::System.EventHandler (this.OnButtonOpenClicked);
		this.saveAction.Activated += new global::System.EventHandler (this.OnButtonSaveClicked);
		this.ApplyAction.Activated += new global::System.EventHandler (this.OnButtonApplyClicked);
	}
}
